global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nginx-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "prometheus-node-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus-node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets: ["cadvisor:8080"]
